name: My multi workflow 

on: push

jobs:
  build_job_1: 

    runs-on: ubuntu-latest
    steps:
    - name: Install cowsay program
      run: sudo apt-get install cowsay -y

    - name: Execute cowsay CMD
      run: cowsay -f dragon "Run for cover, I am a dragon. RRWWR" >> dragon.txt

    - name: sleep for 30 seconds
      run: sleep 30

  test_job_2:
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 10 seconds
      run: sleep 10

    - name: Test file exists
      run: grep -i "dragon" dragon.txt

  deploy_job_3:
    runs-on: ubuntu-latest
    steps:
    - name: Read the file
      run: cat dragon.txt

    - name: deploy
      run: echo Deploying ... .. .